### ISSUE TITLE
Chunk loading

### ISSUE THREAD

**Issue by SilSpd** [LunarEclipseStudios/From-The-Fog#1]
MC version: 1.19.2
FTF version: 1.4

Using Fabric.

Issue: When loading new chunks in worlds that have chunks disabled (such as the Debug World) or loading new chunks in worlds set to Large Biomes, FTF overrides the world settings and uses its own world generation.

Description: I have a Large biome world where I now have sheered cliffs, sudden biome changes, and other world generation issues now that FTF is running. It seems to override the Large Biome setting of the world and uses its own chunk and biome generation technique. Also the developer Debug World now has FTF chunks/biomes loading in the far distance where there should not be any world loading at all.

Proposed solution: Allow for an option in the FTF settings menu to disable any world generation features, leaving only the appearance of Herobrine as the mod feature, removing any and all effects on world generation.

**Comment by Bret06** [comment]
We have been aware of this for a while. It was something we couldn't avoid with the leafless groves. However, it will be fixed in the upcoming v1.5 update. So if you want to remove the data pack from your world you can use this tool. https://www.lunareclipse.studio/creations/from-the-fog#fix-tool
