### ISSUE TITLE
"Is the server overloaded?" yeah, Herobrine is near.

### ISSUE THREAD

**Issue by avinell** [LunarEclipseStudios/From-The-Fog#14]
It may seem strange, but I've been playing with your mod in hardcore for +250 days in game, and some time ago I started having strange problems with the internal server in single player. I noticed this when the blocks began to break badly and all entities noticeably twitch, pretty quickly I realized that this happens every time Herobrine appears somewhere. _I tried to remove all mods, change settings and even looked into the game files, but I could not find what it could be connected with._

The problem is not critical, but sometimes the ping exceeded 300ms and I had to remove the mod and wait for the update, because it was not possible to solve the problem on my own. 

![3456](https://user-images.githubusercontent.com/86418028/236707123-44d3c1fd-0392-4493-8173-852ff572dd05.PNG)
![tr45](https://user-images.githubusercontent.com/86418028/236707127-149cd603-d621-4b1b-9616-813ceaf6cb36.PNG)

![image](https://user-images.githubusercontent.com/86418028/236706755-b3bc00aa-d392-46af-95f9-ddbd9042b190.png)

**Comment by avinell** [comment]
oooo my god datapack why why... maybe is it because my world is too big?
![2023-05-08_02 38 02](https://user-images.githubusercontent.com/86418028/236708232-19e7d52a-7107-4c52-a20b-679fe0337ac2.png)

**Comment by Bret06** [comment]
Noted and fixed in 1.9.
