### ISSUE TITLE
herobrine model broken

### ISSUE THREAD

**Issue by Resistence8** [LunarEclipseStudios/From-The-Fog#16]
everytime i see him, his full model doesnt show up and its broken, im not sure if its the mod but yea

**Comment by Bret06** [comment]
Please read the website before reporting bugs, you need to enable the resourcepack.

**Comment by Resistence8** [comment]
oh

**Comment by andrewgosselin** [comment]
The mod authors seem to not know how to reply to github issues properly.
I had this issue with the non datapack version, you have to move "mod resources" in resource packs all the way to the top priority.
