### ISSUE TITLE
Herobrine has stopped doing events after running commands

### ISSUE THREAD

**Issue by FirstFandomFangirl** [LunarEclipseStudios/From-The-Fog#19]
I have been running the datapack on a small 1.19.2 server for me and a couple of friends. At some point I discovered that I could run commands such as creating a fake Herobrine, or forcing events. Since then, however, he has stopped doing any events by himself. I've set sighting chance to most common and afked waiting for him to appear, nothing happens.

Also unrelated, even while he was doing events normally, I never got signs appearing despite having them enabled in the config. A friend of mine has been playing and getting lots of signs. Not sure if they were maybe nerfed in an update at some point or if I was just getting really unlucky.

**Comment by Bret06** [comment]
> I have been running the datapack on a small 1.19.2 server for me and a couple of friends. At some point I discovered that I could run commands such as creating a fake Herobrine, or forcing events. Since then, however, he has stopped doing any events by himself. I've set sighting chance to most common and afked waiting for him to appear, nothing happens.
> 
> 
> 
> Also unrelated, even while he was doing events normally, I never got signs appearing despite having them enabled in the config. A friend of mine has been playing and getting lots of signs. Not sure if they were maybe nerfed in an update at some point or if I was just getting really unlucky.

Having a fake herobrine spawned does stop him from spawning so be sure to remove that. Also yes the sign chance did get nerfed.

Please use our discord to ask questions next time.
