### ISSUE TITLE
Server console weird output

### ISSUE THREAD

**Issue by k2helix** [LunarEclipseStudios/From-The-Fog#2]
Hi, I installed From the fog as a Fabric mod on my server and now the console outputs some things weirdly. Here you can see an example:
![image](https://user-images.githubusercontent.com/49949593/219949983-99e7cd61-fef9-4761-95c3-5037ae12cc50.png)

Is is caused by From the fog as removing it solves the problem. I had a similar issue with Ultris, which is also a mod that can be installed as a datapack, but it was as a Fabric mod and same thing happened

**Comment by Bret06** [comment]
Datapacks compiled as fabric mods act weird on servers
Be sure to use the datapack on your server
but have people install from the fog as a mod 
it will apply the rp for them
