### ISSUE TITLE
Decreased Mob Spawns

### ISSUE THREAD

**Issue by ThatOneHuman27** [LunarEclipseStudios/From-The-Fog#21]
Mob spawning seems to tank downwards with this pack. Even bumping it up to hard difficulty for a couple of hours I have not seen any noticeable increase in mobs. I can regularly AFK in the middle of a plains biome at night and I will be untouched when I come back. I've flown around with spectator and still barely saw anything, in or out of caves. I see like 3 zombies every hour and thats about it.

**Comment by Bret06** [comment]
This is not caused by From The Fog, be sure to check your other mods, datapacks, or plugins.
