### ISSUE TITLE
"Unable to add mob to team 'nocol' (that team probably doesn't exist)"

### ISSUE THREAD

**Issue by trojan-xs** [LunarEclipseStudios/From-The-Fog#28]
![image](https://github.com/LunarEclipseStudios/From-The-Fog/assets/49181542/8d042cb5-a51a-42ef-a921-61911e0772b6)

Running on latest Paper 1.20.1 version 90.
Nothing else installed.

Is this an issue I should be concerned about?

**Comment by Bret06** [comment]
It's nothing, it is because some server jars prevent mobs from being added to teams on summon.
