### ISSUE TITLE
I've waited a few days on a new world and nothing has happened.

### ISSUE THREAD

**Issue by Autumnfoxbrr** [LunarEclipseStudios/From-The-Fog#3]
I've waited a while, and absoloutely no events have happened. I've gone into fromthefog>data>fromthefog>functions>admin>default_config and changed the delay to off, but that hasn't worked. And it has showed up on the mod menu ingame, so I assume it isn't an incompat issue, though I am on 1.19.3 fabric if that helps.

**Comment by Bret06** [comment]
It's almost never a case that nothing has happened. Instead, it's a matter of what you've noticed. Also, do NOT directly edit the datapack files. The config is a command run in-game, `/function fromthefog:admin/config`.
