### ISSUE TITLE
Ability to cause herobrine to not haunt until ritual is used

### ISSUE THREAD

**Issue by KyleBeep** [LunarEclipseStudios/From-The-Fog#30]
This would be nice as a configuration option, as well as a ritual to get rid of him

**Comment by ryleu** [comment]
you could set the haunting delay to a massively high number... maybe something like this command?
```
scoreboard players set dayDelayConfig ftf.config 1000000
```

**Comment by Bret06** [comment]
This can already be achieved by disabling haunting delay. If you have further suggestions please put them on our [Discord](https://discord.lunareclipse.studio/).
