### ISSUE TITLE
Ally Scream Sound Effect Upon a Close Encouter (I think this is a feture i cant hear)

### ISSUE THREAD

**Issue by UnClausus-Ludi** [LunarEclipseStudios/From-The-Fog#32]
Also turn up the scream noise

**Comment by Deus-Scissuras** [comment]
You know why i want this added

**Comment by Bret06** [comment]
Thank you for the suggestion! However, it takes longer for it to get seen here. Be sure to join our [Discord ](https://discord.lunareclipse.studio)to make future suggestions.
