### ISSUE TITLE
[Request] Adjusting haunt delay

### ISSUE THREAD

**Issue by FiendBartimaeus** [LunarEclipseStudios/From-The-Fog#35]
This mod is amazing, one of my friends keeps getting jumpscared by herobrine and I love how freaked out they get. He's even spooked me a few times too!   

However, I'm afraid that it's possible that we may end up getting too used to him showing up. I'm in charge of the server, and I'd like to have a 'breather' where he doesn't show up at all for a good amount of ingame days (thinking like 200-300 or something), just enough time for people to forget about him and then he'll start showing up again.  

I figured I could do this by adjusting the haunting delay, but I can't find an easy way to set it to something like 1500 days without manually clicking the increase haunting delay button 1500 times. 

Would it be possible to add in a shift or control modifier when clicking to increase the delay by days of 10s and 100s or something? Alternatively, a button that tells Herobrine to rest for a certain number of days would work too.  

Thank you for all the work on this mod it's truly a blast!

**Comment by ryleu** [comment]
if you want to change it to an arbitrary number, you can use this command:

```mcfunction
scoreboard players set dayDelayConfig ftf.config 0
```

replace `0` with the number of days you want

**Comment by Bret06** [comment]
> if you want to change it to an arbitrary number, you can use this command:
> 
> ```mcfunction
> scoreboard players set dayDelayConfig ftf.config 0
> ```
> 
> replace `0` with the number of days you want

That isn't the correct scoreboard, but that you for your help anyway.
It is actually:
```mcfunction
scoreboard players set dayDelayConfig ftf.configOptions 0
```
