### ISSUE TITLE
where are configs saved

### ISSUE THREAD

**Issue by MoRoN222** [LunarEclipseStudios/From-The-Fog#36]
the mod version unfortunately doesn't use actual mod configs but instead does it with the function command, I want to know if they and if yes, where they are saved, and if they will get saved on all worlds equally or not

**Comment by ryleu** [comment]
they won't be saved on all worlds, but you can use the mod global packs to create a datapack that runs your config commands when the world loads

something like this: https://github.com/ryleu/spooky-scary-modpack/tree/main/global_packs/required_data/spooky

**Comment by MoRoN222** [comment]
alright
