### ISSUE TITLE
husk zombie inside herobrine (1.20.2)

### ISSUE THREAD

**Issue by ajsaccount123** [LunarEclipseStudios/From-The-Fog#38]
kinda self explanatory but to explain it further, whenever herobrine spawns theres a zombie husk (baby i think?) inside of him, maybe forgot the code to set it invisible. Played with the data-resource pack on multiplayer
![2023-10-29_23 14 13](https://github.com/LunarEclipseStudios/From-The-Fog/assets/64874321/b8d1d4cb-5708-454f-841e-8b848f785f13)
![2023-10-29_23 24 03](https://github.com/LunarEclipseStudios/From-The-Fog/assets/64874321/8cc1dac0-217e-4490-a477-0f443b84c00a)
![2023-10-29_23 42 52](https://github.com/LunarEclipseStudios/From-The-Fog/assets/64874321/530ddd49-dcd1-4f2e-9fc3-a9d4bf8774a5)
![2023-10-29_23 43 33](https://github.com/LunarEclipseStudios/From-The-Fog/assets/64874321/510ac7d0-c57f-4c71-8192-7440b2606b49)

![2023-10-29_23 42 56](https://github.com/LunarEclipseStudios/From-The-Fog/assets/64874321/f9f355e5-4937-4dbb-9448-510ad5e57d93)

**Comment by AgentLoneStar007** [comment]
Same here for me.
![image](https://github.com/LunarEclipseStudios/From-The-Fog/assets/57960152/d436e441-160d-4125-9342-7129458faab3)

**Comment by luckydoggo** [comment]
Don't quote me on this, but I believe this to be caused by the `ActiveEffects` NBT tag being renamed `active_effects` in 1.20.2

**Comment by MAXimized490** [comment]
Having this issue as well.

**Comment by Bret06** [comment]
Please check for answers on our [Discord](https://discord.lunareclipse.studio) before leaving new reports.
