### ISSUE TITLE
Field of view problems 

### ISSUE THREAD

**Issue by Turachkh** [LunarEclipseStudios/From-The-Fog#8]
It appears that herobrine's detection checking assumes the default fov. This means, that herobrine can be visible in the periphery for portions of time, when the fov is high and likewise will disappear too quickly to be glimpsed in low fov. This is bound to break the immersion for many a player. Please see to ameliorating this somehow.

**Comment by Bret06** [comment]
This isn't a bug and hardly breaks the immersion unless the player uses Quake pro.
